spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=borrow;encrypt=false
    username: ${DATABASE_ADMIN}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  sql:
    init:
      mode: always
file:
  upload-dir: uploads
